### ISSUE TITLE
使用图片

### ISSUE THREAD

**Issue by Yi-Lyu** [pangee/Migrating-from-PHP5.6.x-to-PHP7.0.x#1]
![image](https://cloud.githubusercontent.com/assets/1308846/9434941/01402560-4a76-11e5-9943-f9f153745030.png)

**Comment by Yi-Lyu** [comment]
![image](https://cloud.githubusercontent.com/assets/1308846/9435404/1bf947a2-4a7a-11e5-97bb-96677cc560fb.png)

**Comment by pangee** [comment]
![Uploading image.png…]()

**Comment by Yi-Lyu** [comment]
![image](https://cloud.githubusercontent.com/assets/1308846/9438212/bdeec078-4a8e-11e5-91b5-5e6b92e4019d.png)
